---
#-------------------------------
# General Site Settings
title: Sejong-Overflow Docs
logo: logo.svg # You can add own logo.
description: Sejong-Overflow Docs

#-------------------------------
# Author Settings
author:
  name: Sejong-Overflow Team
  image: about_page.png
  say-hello: <strong>Sejong-Overflow</strong>
  bio: Sejong-Overflow solves the difficulties that Sejong University students encounter while studying programming. <br><ul><li>Communities that grow through questions and answers</li> <li>Sharing information related to programming activities</li> <li>User-based system For further <a href="https://sejong-overflow.readthedocs.io/en/latest/">details</a>, please refer to Features</li></ul>

#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
